import Foundation

@main
struct FileBatchSmoke {
    static func main() throws {
        let manager = FileManager.default
        let base = URL(fileURLWithPath: CommandLine.arguments[1], isDirectory: true)
        if manager.fileExists(atPath: base.path) {
            try manager.removeItem(at: base)
        }
        try manager.createDirectory(at: base, withIntermediateDirectories: true)

        let root = base.appendingPathComponent("documents", isDirectory: true)
        let store = try FileStore(root: root)
        let photo = root.appendingPathComponent("photo.PNG")
        let book = root.appendingPathComponent("book.EPUB")
        let unknown = root.appendingPathComponent("unknown")
        let shared = root.appendingPathComponent("共享/shared.PNG")
        let outside = base.appendingPathComponent("outside.PNG")
        let outsideLink = root.appendingPathComponent("outside-link.PNG")
        let existing = root.appendingPathComponent("图片/photo.PNG")
        let importFolder = root.appendingPathComponent("Downloads", isDirectory: true)
        let importSource = base.appendingPathComponent("import.txt")
        let existingImport = importFolder.appendingPathComponent("import.txt")
        let missingImport = base.appendingPathComponent("missing-import.txt")
        try Data("new photo".utf8).write(to: photo)
        try Data("book".utf8).write(to: book)
        try Data("unknown".utf8).write(to: unknown)
        try Data("shared".utf8).write(to: shared)
        try Data("outside".utf8).write(to: outside)
        try Data("existing photo".utf8).write(to: existing)
        try Data("import source".utf8).write(to: importSource)
        try Data("original import".utf8).write(to: existingImport)
        try manager.createSymbolicLink(at: outsideLink, withDestinationURL: outside)

        assert(store.canGroup(photo))
        assert(!store.canGroup(unknown))
        assert(!store.canGroup(shared))
        assert(!store.canGroup(outsideLink))
        assert(!store.canGroup(root.appendingPathComponent("文稿")))

        let imported = store.importFiles([importSource, missingImport], into: importFolder)
        assert(imported.succeeded.count == 1)
        assert(imported.succeeded[0].lastPathComponent == "import 2.txt")
        assert(imported.failures.count == 1 && imported.failures[0].url == missingImport)
        assert(imported.skipped.isEmpty)
        try assertBytes("import source", at: imported.succeeded[0])
        try assertBytes("original import", at: existingImport)

        let grouped = store.perform(.group, on: [photo, book, unknown, outsideLink, shared])
        assert(grouped.succeeded.count == 2)
        assert(grouped.skipped.count == 2)
        assert(grouped.failures.count == 1)
        assert(grouped.skipped == [unknown, shared])
        assert(grouped.failures[0].url == outsideLink)
        assert(grouped.succeeded[0].lastPathComponent == "photo 2.PNG")
        assert(grouped.succeeded[1].path == root.appendingPathComponent("电子书/book.EPUB").path)
        try assertBytes("new photo", at: grouped.succeeded[0])
        try assertBytes("book", at: grouped.succeeded[1])
        try assertBytes("existing photo", at: existing)
        try assertBytes("unknown", at: unknown)
        try assertBytes("shared", at: shared)
        try assertBytes("outside", at: outside)
        assert(manager.fileExists(atPath: outsideLink.path))

        let nestedFolder = try store.createFolder(named: "Other", in: root)
        let nestedPhoto = nestedFolder.appendingPathComponent("nested-photo.PNG")
        try Data("nested photo".utf8).write(to: nestedPhoto)
        assert(store.canGroup(nestedPhoto))
        let nestedGroup = store.perform(.group, on: [nestedPhoto])
        assert(nestedGroup.succeeded.count == 1)
        assert(nestedGroup.skipped.isEmpty)
        assert(nestedGroup.failures.isEmpty)
        try assertBytes("nested photo", at: root.appendingPathComponent("图片/nested-photo.PNG"))
        assert(!manager.fileExists(atPath: nestedPhoto.path))

        let downloadPhoto = importFolder.appendingPathComponent("download.PNG")
        try Data("download".utf8).write(to: downloadPhoto)
        let nestedDownload = try store.createFolder(named: "nested", in: importFolder)
        let nestedDownloadPhoto = nestedDownload.appendingPathComponent("nested.PNG")
        try Data("nested download".utf8).write(to: nestedDownloadPhoto)
        let nestedShared = try store.createFolder(named: "nested", in: root.appendingPathComponent("共享"))
        let nestedSharedPhoto = nestedShared.appendingPathComponent("nested.PNG")
        try Data("nested shared".utf8).write(to: nestedSharedPhoto)
        assert(!store.canGroup(downloadPhoto))
        assert(!store.canGroup(nestedDownloadPhoto))
        assert(!store.canGroup(nestedSharedPhoto))
        let excludedGroup = store.perform(.group, on: [downloadPhoto, nestedDownloadPhoto, shared, nestedSharedPhoto])
        assert(excludedGroup.succeeded.isEmpty)
        assert(excludedGroup.skipped == [downloadPhoto, nestedDownloadPhoto, shared, nestedSharedPhoto])
        assert(excludedGroup.failures.isEmpty)
        try assertBytes("download", at: downloadPhoto)
        try assertBytes("nested download", at: nestedDownloadPhoto)
        try assertBytes("shared", at: shared)
        try assertBytes("nested shared", at: nestedSharedPhoto)

        let missing = root.appendingPathComponent("missing.txt")
        let copied = store.perform(.copy(to: root.appendingPathComponent("文稿")), on: [unknown, missing])
        assert(copied.succeeded.count == 1)
        assert(copied.skipped.isEmpty)
        assert(copied.failures.count == 1 && copied.failures[0].url == missing)
        try assertBytes("unknown", at: copied.succeeded[0])
        try assertBytes("unknown", at: unknown)

        let folder = try store.createFolder(named: "parent", in: root)
        let child = try store.createFolder(named: "child", in: folder)
        let nested = folder.appendingPathComponent("keep.txt")
        try Data("keep".utf8).write(to: nested)
        let invalidMove = store.perform(.move(to: child), on: [folder])
        assert(invalidMove.succeeded.isEmpty && invalidMove.skipped.isEmpty)
        assert(invalidMove.failures.count == 1 && invalidMove.failures[0].url == folder)
        try assertBytes("keep", at: nested)
        assert(manager.fileExists(atPath: child.path))

        let keep = root.appendingPathComponent("keep.txt")
        let remove = root.appendingPathComponent("remove.txt")
        try Data("keep".utf8).write(to: keep)
        try Data("remove".utf8).write(to: remove)
        let deleted = store.perform(.delete, on: [remove])
        assert(deleted.succeeded == [remove])
        assert(deleted.skipped.isEmpty && deleted.failures.isEmpty)
        assert(!manager.fileExists(atPath: remove.path))
        try assertBytes("keep", at: keep)

        print("FileBatch smoke passed")
    }

    private static func assertBytes(_ expected: String, at url: URL) throws {
        let bytes = try Data(contentsOf: url)
        assert(bytes == Data(expected.utf8))
    }
}
